name: MinewebAuthPlugin
author: Fir3rl
version: 1.0
main: fr.fir3rl.authplugin.AuthPlugin
commands:
  login: 
    description: Permet de se connecter via Mineweb
  forcelogin: 
    description: Forcez la connexion d'un joueur
    permission: authplugin.admin.forcelogin
  unlock:
    permission: authplugin.admin.unlock
  authversion:
    description: Donne la version du plugin
